PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE greetings (id primary key,greeting text);
INSERT INTO "greetings" VALUES(NULL,'aloha!');
INSERT INTO "greetings" VALUES(NULL,'привееееееет!');
INSERT INTO "greetings" VALUES(NULL,'превед!');
INSERT INTO "greetings" VALUES(NULL,'здравствуй! ик');
INSERT INTO "greetings" VALUES(NULL,'опять ты?! ур-раааааа!');
INSERT INTO "greetings" VALUES(NULL,'тарам-пам-пам, смотрите кто зашёл!');
INSERT INTO "greetings" VALUES(NULL,'ухххх, кто к нам пришёл!');
INSERT INTO "greetings" VALUES(NULL,'ну что? поболтаем?');
INSERT INTO "greetings" VALUES(NULL,'hi!');
INSERT INTO "greetings" VALUES(NULL,'на сцене суперзвезда!');
INSERT INTO "greetings" VALUES(NULL,'я сегодня вся такая пьяная');
INSERT INTO "greetings" VALUES(NULL,'поцелуй меня!');
INSERT INTO "greetings" VALUES(NULL,'Inri, Inri, Abracadabra!');
INSERT INTO "greetings" VALUES(NULL,'хи-хи-хи-ха-ха-ХААААААА!');
INSERT INTO "greetings" VALUES(NULL,'поздно пришёл - пиво уже закончилось, не сбегаешь, а?');
INSERT INTO "greetings" VALUES(NULL,'welcome toooo hell!');
INSERT INTO "greetings" VALUES(NULL,'тарам пам пам, плус адын');
CREATE TABLE regexp (id primary key,regexp text,reaction text,is_command integer);
INSERT INTO "regexp" VALUES(NULL,'ircyka.*хуй','я с вами совсем одичаю, разучусь материться и стану словой @#$ писать через чёрточку',0);
INSERT INTO "regexp" VALUES(NULL,'ircyka.*хуй','йух!',0);
INSERT INTO "regexp" VALUES(NULL,'ircyka','не грузи меня, я не сухогруз! я танкер, налей мне!',0);
INSERT INTO "regexp" VALUES(NULL,'ircyka.*тыц','клац!',0);
INSERT INTO "regexp" VALUES(NULL,'ircyka.*фыва','олдж!',0);
INSERT INTO "regexp" VALUES(NULL,'ircyka.*пинг','понг',0);
INSERT INTO "regexp" VALUES(NULL,'ircyka.*ping','pong',0);
INSERT INTO "regexp" VALUES(NULL,'ircyka: version',"I'm best of the best!",0);
COMMIT;
